add RTAU inquiry endpoint and rework example to TS
pagos-ai/loon-js-example pull request #7
Opened 2024-04-22 12:23 UTC by k-kirill-s

2024-04-23 05:24 UTC, latompa requested changes

2024-04-23 05:24 UTC, latompa commented on src/lib/encryption/auth.ts
move this file to src/lib/auth.ts, since it doesn't do encryption

2024-04-23 05:24 UTC, latompa commented on README.md
> +| submerchant_account_id | optional value, alphanumeric              |
keep the `optional, max 12 characters for visa/discover/american express, exactly 15 characters for mastercard` part, since it's specific to mastercard
keep the metadata field too

2024-04-23 05:24 UTC, latompa commented on README.md
swap the section order of
```
## Get Job Results
## RTAU inquiry
### Sample response file format
``` 

to
```
## Get Job Results
### Sample response file format
## RTAU inquiry
```

2024-04-23 05:24 UTC, latompa commented on README.md
can you add a note on how to get tsx running locally, i didn't get tsx in my PATH after `npm install`, had to run `npx tsx some_file.ts`

2024-04-23 05:24 UTC, latompa commented on README.md
where RTAU is mentioned first time, maybe say Real Time Account Updater (RTAU), to introduce the term

2024-04-24 05:56 UTC, latompa commented
the environment variable validation requires both batch and rtau creds atm,
we should allow batch calls to not have to have rtau creds and vice versa

2024-04-25 08:21 UTC, k-kirill-s commented on src/lib/encryption/auth.ts
make different file naming:
- lib to utils
- auth.ts moved to utils

2024-04-25 08:21 UTC, k-kirill-s commented on README.md
> +| submerchant_account_id | optional value, alphanumeric              |
thanks, looks like lost it during conflict solving, also added metadata field

2024-04-25 08:24 UTC, k-kirill-s commented on README.md
got the point, fixed

2024-04-25 08:25 UTC, k-kirill-s commented on README.md
added `for tsx usage install it globally with 'npm install -G tsx' or add 'npx' to each 'tsx' for local execution`

2024-04-25 08:29 UTC, k-kirill-s commented on README.md
added this, good notice. It would be also great to add link to some documentation, but as far as I see, there is no public version for now.

2024-04-25 08:41 UTC, k-kirill-s commented on README.md
added this, good notice. It would be also great to add link to some documentation, but as far as I see, there is no public version for now.

2024-04-25 08:43 UTC, k-kirill-s commented
@latompa regarding your comment with env variable, i've added  to readme phrase`copy `.env.example` to `.env` and populate the keys with your credentials. if you don't have some of credentials for batch or RTAU, just leave original place holder string.` Will it be fine?

2024-04-25 15:37 UTC, latompa approved these changes

2024-04-25 15:40 UTC, merged